#!/usr/bin/env python3
"""Regenerate src/loader_exports.h: every xr* command in openxr.h + openxr_platform.h, as an X-macro list.
The loader shim (src/loader_shim.cpp) exports each one as a trampoline into the game's original loader.
  python3 vr-bridge/quest-layer/gen_exports.py <OpenXR-SDK>/include/openxr"""
import re
import sys
from pathlib import Path

inc = Path(sys.argv[1])
names = set()
for h in ("openxr.h", "openxr_platform.h"):
    names |= set(re.findall(r"XRAPI_ATTR\s+\w+\s+XRAPI_CALL\s+(xr\w+)\s*\(", (inc / h).read_text()))
names = sorted(names)
# Implemented in C++ by the shim (they go through the XEMS layer); everything else is a plain trampoline.
OWN = {"xrGetInstanceProcAddr", "xrCreateInstance", "xrDestroyInstance", "xrApplyHapticFeedback",
       "xrStopHapticFeedback", "xrPollEvent", "xrDestroyAction"}
fwd = [n for n in names if n not in OWN]
out = Path(__file__).resolve().parent / "src" / "loader_exports.h"
out.write_text(
    "// Generated by gen_exports.py — every xr* command of openxr.h + openxr_platform.h (" + str(len(names)) + ").\n"
    "// X(index, name). Used by loader_shim.cpp; xems_vr_patch.py checks the game's loader exports nothing else.\n"
    "#define XEMS_LOADER_FORWARDS(X) \\\n" + " \\\n".join(f"    X({i}, {n})" for i, n in enumerate(fwd)) + "\n"
    f"#define XEMS_LOADER_FORWARD_COUNT {len(fwd)}\n")
(Path(__file__).resolve().parent / "src" / "loader_exports.txt").write_text("\n".join(names) + "\n")
print(len(names), "->", out)
