package com.isaigu.gymapp.ai;

/** GENERATED by scripts/gen-exercises.py from branding/exercises/*.json — do not edit. */
final class AutoTemplateData {
    private AutoTemplateData() {}

    /** Exercise ids (branding/exercises/exercises.json order), Bulgarian and English names, position. */
    static final String[] IDS = {"banded-lat-pulldown", "bench-dip", "bicycle-crunch", "bodyweight-squat", "bulgarian-split-squat", "burpee", "chair-dip", "crunch", "curtsy-lunge", "donkey-kick", "dumbbell-lateral-lunge", "dumbbell-overhead-tricep-extension", "dumbbell-side-bend", "dumbbell-sumo-squat", "elliptical", "fire-hydrant", "forward-lunge", "glute-bridge", "goblet-squat", "incline-push-up", "jump-squat", "jumping-jack", "kettlebell-romanian-deadlift", "kettlebell-swing", "knee-push-up", "lateral-lunge", "lying-leg-raise", "one-arm-dumbbell-row", "plank", "plank-shoulder-tap", "plate-front-raise", "reverse-crunch", "reverse-lunge", "side-lying-hip-abduction", "side-plank", "single-leg-glute-bridge", "standing-dumbbell-press", "step-down", "superman", "tricep-kickback"};
    static final String[] BG = {"Теглене надолу с ластик", "Кофички на пейка", "Велосипед (коремни преси)", "Клек без тежест", "Български клек", "Бърпи", "Кофички на стол", "Коремни преси", "Реверанс напади", "Ритник назад от колене", "Странични напади с дъмбел", "Разгъване за трицепс над главата с дъмбел", "Странично навеждане с дъмбел", "Сумо клек с дъмбел", "Кардио тренажор", "Отвеждане на коляното встрани (от колене)", "Напади напред", "Глутеус мост", "Гоблет клек (с дъмбел пред гърдите)", "Лицеви опори с ръце на пейка", "Клек с отскок", "Джъмпинг джак", "Румънска тяга с пудовка", "Суинг с пудовка", "Лицеви опори от колене", "Странични напади", "Вдигане на краката от лег", "Гребане с дъмбел с една ръка", "Планк", "Планк с докосване на рамото", "Предно вдигане с диск", "Обратни коремни преси", "Напади назад", "Отвеждане на крака от лег на страна", "Страничен планк", "Глутеус мост на един крак", "Раменна преса с дъмбели (прав)", "Слизане от пейка", "Супермен", "Трицепсов ритник с дъмбел"};
    static final String[] EN = {"Banded Lat Pulldown", "Bench Dip", "Bicycle Crunch", "Bodyweight Squat", "Bulgarian Split Squat", "Burpee", "Chair Dip", "Crunch", "Curtsy Lunge", "Donkey Kick", "Dumbbell Lateral Lunge", "Dumbbell Overhead Tricep Extension", "Dumbbell Side Bend", "Dumbbell Sumo Squat", "Elliptical", "Fire Hydrant", "Forward Lunge", "Glute Bridge", "Goblet Squat", "Incline Push-up", "Jump Squat", "Jumping Jack", "Kettlebell Romanian Deadlift", "Kettlebell Swing", "Knee Push-up", "Lateral Lunge", "Lying Leg Raise", "One-Arm Dumbbell Row", "Plank", "Plank Shoulder Tap", "Plate Front Raise", "Reverse Crunch", "Reverse Lunge", "Side-Lying Hip Abduction", "Side Plank", "Single-Leg Glute Bridge", "Standing Dumbbell Press", "Step-Down", "Superman", "Tricep Kickback"};
    static final String[] POS = {"stand", "bench", "floor", "stand", "bench", "stand", "bench", "floor", "stand", "floor", "stand", "stand", "stand", "stand", "machine", "floor", "stand", "floor", "stand", "bench", "stand", "stand", "stand", "stand", "floor", "stand", "floor", "bench", "floor", "floor", "stand", "floor", "stand", "floor", "floor", "floor", "stand", "bench", "floor", "stand"};

    /** Auto-catalog program id → stations per level 1..3 (null = no such level). */
    static final String[] PROGRAMS = {"general", "glutes", "core", "power", "cardio", "back_active", "senior"};
    static final String[][][] STATIONS = {
            {{"bodyweight-squat", "banded-lat-pulldown", "forward-lunge", "incline-push-up", "chair-dip", "glute-bridge", "crunch", "plank"}, {"goblet-squat", "reverse-lunge", "standing-dumbbell-press", "dumbbell-overhead-tricep-extension", "one-arm-dumbbell-row", "knee-push-up", "glute-bridge", "bicycle-crunch", "plank-shoulder-tap"}, {"kettlebell-romanian-deadlift", "standing-dumbbell-press", "dumbbell-lateral-lunge", "bulgarian-split-squat", "one-arm-dumbbell-row", "bench-dip", "plank-shoulder-tap", "lying-leg-raise"}},   // general
            {{"bodyweight-squat", "step-down", "glute-bridge", "side-lying-hip-abduction", "donkey-kick", "fire-hydrant"}, {"dumbbell-sumo-squat", "reverse-lunge", "curtsy-lunge", "lateral-lunge", "single-leg-glute-bridge", "donkey-kick", "fire-hydrant"}, {"kettlebell-romanian-deadlift", "dumbbell-lateral-lunge", "kettlebell-swing", "jump-squat", "curtsy-lunge", "bulgarian-split-squat", "single-leg-glute-bridge"}},   // glutes
            {{"crunch", "reverse-crunch", "plank", "side-plank", "superman", "glute-bridge"}, {"dumbbell-side-bend", "bicycle-crunch", "lying-leg-raise", "plank-shoulder-tap", "side-plank", "superman", "reverse-crunch"}, {"dumbbell-side-bend", "lying-leg-raise", "bicycle-crunch", "plank-shoulder-tap", "side-plank", "reverse-crunch", "plank", "superman"}},   // core
            {null, {"jump-squat", "knee-push-up", "kettlebell-swing", "forward-lunge", "jumping-jack", "one-arm-dumbbell-row"}, {"jump-squat", "burpee", "kettlebell-swing", "plank-shoulder-tap", "reverse-lunge", "jumping-jack", "standing-dumbbell-press"}},   // power
            {{"elliptical", "bodyweight-squat", "step-down", "lateral-lunge", "glute-bridge"}, {"jumping-jack", "bodyweight-squat", "forward-lunge", "plank-shoulder-tap", "lateral-lunge", "elliptical"}, {"burpee", "jump-squat", "jumping-jack", "kettlebell-swing", "reverse-lunge", "plank-shoulder-tap", "dumbbell-lateral-lunge"}},   // cardio
            {{"banded-lat-pulldown", "bodyweight-squat", "glute-bridge", "superman", "plank", "side-plank"}, {"banded-lat-pulldown", "one-arm-dumbbell-row", "single-leg-glute-bridge", "superman", "plank-shoulder-tap", "side-plank"}, {"kettlebell-romanian-deadlift", "goblet-squat", "banded-lat-pulldown", "one-arm-dumbbell-row", "superman", "side-plank", "plank-shoulder-tap"}},   // back_active
            {{"bodyweight-squat", "banded-lat-pulldown", "incline-push-up", "step-down", "glute-bridge", "side-lying-hip-abduction"}, {"goblet-squat", "standing-dumbbell-press", "forward-lunge", "incline-push-up", "one-arm-dumbbell-row", "glute-bridge"}, {"goblet-squat", "standing-dumbbell-press", "reverse-lunge", "plate-front-raise", "tricep-kickback", "one-arm-dumbbell-row", "knee-push-up"}},   // senior
    };

    /** Client state (the form's keys) → exercises it rules out, and what may replace them (in order). */
    static final String[] COND = {"knees", "back", "neck", "diastasis", "postpartum", "osteo", "joints"};
    static final String[][] AVOID = {
            {"jump-squat", "burpee", "bulgarian-split-squat", "forward-lunge", "reverse-lunge", "curtsy-lunge", "lateral-lunge", "dumbbell-lateral-lunge", "jumping-jack", "step-down"},
            {"kettlebell-swing", "kettlebell-romanian-deadlift", "lying-leg-raise", "burpee", "jump-squat", "bicycle-crunch", "crunch"},
            {"standing-dumbbell-press", "dumbbell-overhead-tricep-extension", "crunch", "bicycle-crunch", "plate-front-raise"},
            {"crunch", "bicycle-crunch", "reverse-crunch", "lying-leg-raise", "plank-shoulder-tap", "plank", "burpee"},
            {"crunch", "bicycle-crunch", "reverse-crunch", "lying-leg-raise", "plank-shoulder-tap", "plank", "jump-squat", "burpee", "jumping-jack", "kettlebell-swing"},
            {"jump-squat", "burpee", "jumping-jack", "kettlebell-swing", "crunch", "bicycle-crunch"},
            {"jump-squat", "burpee", "jumping-jack", "kettlebell-swing"},
    };
    static final String[][] INSTEAD = {
            {"glute-bridge", "single-leg-glute-bridge", "side-lying-hip-abduction", "donkey-kick", "fire-hydrant", "bodyweight-squat"},
            {"glute-bridge", "side-plank", "plank", "banded-lat-pulldown", "side-lying-hip-abduction"},
            {"reverse-crunch", "tricep-kickback", "banded-lat-pulldown", "glute-bridge"},
            {"glute-bridge", "side-lying-hip-abduction", "fire-hydrant", "donkey-kick", "banded-lat-pulldown"},
            {"glute-bridge", "side-lying-hip-abduction", "fire-hydrant", "donkey-kick", "banded-lat-pulldown", "bodyweight-squat"},
            {"bodyweight-squat", "glute-bridge", "step-down", "banded-lat-pulldown", "side-lying-hip-abduction"},
            {"bodyweight-squat", "glute-bridge", "step-down", "side-lying-hip-abduction"},
    };

    /** Focus zone (the form's keys) → an extra station, the first one allowed. */
    static final String[] FOCUS = {"glutes", "abs", "arms", "back", "legs", "chest"};
    static final String[][] FOCUS_EX = {
            {"glute-bridge", "donkey-kick", "single-leg-glute-bridge"},
            {"reverse-crunch", "side-plank", "plank"},
            {"tricep-kickback", "bench-dip", "chair-dip"},
            {"banded-lat-pulldown", "one-arm-dumbbell-row", "superman"},
            {"goblet-squat", "step-down", "lateral-lunge"},
            {"incline-push-up", "knee-push-up"},
    };
}
