#!/usr/bin/env python3
"""branding/exercises/{programs,exercises}.json → ai/AutoTemplateData.java (the template data as plain Java, so the
logic runs on the JVM in scripts/ai-sim too). Run after editing either JSON; commit the generated file.

  python3 scripts/gen-exercises.py
"""
from __future__ import annotations

import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
EX = ROOT / "branding" / "exercises"
OUT = ROOT / "branding" / "java" / "src" / "com" / "isaigu" / "gymapp" / "ai" / "AutoTemplateData.java"


def q(s: str) -> str:
    return '"' + s.replace("\\", "\\\\").replace('"', '\\"') + '"'


def arr(xs) -> str:
    return "{" + ", ".join(q(x) for x in xs) + "}"


def main() -> None:
    prog = json.loads((EX / "programs.json").read_text(encoding="utf-8"))
    exs = json.loads((EX / "exercises.json").read_text(encoding="utf-8"))["exercises"]
    ids = [e["id"] for e in exs]
    known = set(ids)
    L = []
    L.append("package com.isaigu.gymapp.ai;")
    L.append("")
    L.append("/** GENERATED by scripts/gen-exercises.py from branding/exercises/*.json — do not edit. */")
    L.append("final class AutoTemplateData {")
    L.append("    private AutoTemplateData() {}")
    L.append("")
    L.append("    /** Exercise ids (branding/exercises/exercises.json order), Bulgarian and English names, position. */")
    L.append("    static final String[] IDS = " + arr(ids) + ";")
    L.append("    static final String[] BG = " + arr([e["bg"] for e in exs]) + ";")
    L.append("    static final String[] EN = " + arr([e["en"] for e in exs]) + ";")
    L.append("    static final String[] POS = " + arr([e["pos"] for e in exs]) + ";")
    pats = {x["id"]: x["pat"] for x in json.loads((EX / "library-src.json").read_text(encoding="utf-8"))["exercises"]}
    L.append("    /** Movement pattern (library-src.json): the impulse block's starting parameters (Workout.defaults). */")
    L.append("    static final String[] PAT = " + arr([pats.get(e["id"], "squat") for e in exs]) + ";")
    L.append("    /** MET of the movement itself (Compendium-style estimate) and the muscles it works per suit channel")
    L.append("     *  (0 chest, 1 abs, 2 front thigh, 3 calf, 4 arms, 5 shoulders, 6 back, 7 lower back, 8 glutes, 9 back thigh; 100 = main). */")
    L.append("    static final double[] MET = {" + ", ".join(str(float(e["met"])) for e in exs) + "};")
    L.append("    static final int[][] MUS = {")
    for e in exs:
        assert len(e["mus"]) == 10, e["id"]
        L.append("            {" + ", ".join(str(int(v)) for v in e["mus"]) + "},   // " + e["id"])
    L.append("    };")
    L.append("")
    L.append("    /** Auto-catalog program id → stations per level 1..3 (null = no such level). */")
    L.append("    static final String[] PROGRAMS = " + arr([a["id"] for a in prog["active"]]) + ";")
    L.append("    static final String[][][] STATIONS = {")
    for a in prog["active"]:
        rows = []
        for lv in ("1", "2", "3"):
            if lv in a["lv"]:
                st = [s["ex"] for s in a["lv"][lv]["stations"]]
                assert set(st) <= known, (a["id"], set(st) - known)
                rows.append(arr(st))
            else:
                rows.append("null")
        L.append("            {" + ", ".join(rows) + "},   // " + a["id"])
    L.append("    };")
    L.append("")
    conds = list(prog["avoid"].keys())
    L.append("    /** Client state (the form's keys) → exercises it rules out, and what may replace them (in order). */")
    L.append("    static final String[] COND = " + arr(conds) + ";")
    L.append("    static final String[][] AVOID = {")
    for c in conds:
        assert set(prog["avoid"][c]["no"]) <= known and set(prog["avoid"][c]["yes"]) <= known, c
        L.append("            " + arr(prog["avoid"][c]["no"]) + ",")
    L.append("    };")
    L.append("    static final String[][] INSTEAD = {")
    for c in conds:
        L.append("            " + arr(prog["avoid"][c]["yes"]) + ",")
    L.append("    };")
    L.append("")
    focus = list(prog["focusEx"].keys())
    L.append("    /** Focus zone (the form's keys) → an extra station, the first one allowed. */")
    L.append("    static final String[] FOCUS = " + arr(focus) + ";")
    L.append("    static final String[][] FOCUS_EX = {")
    for f in focus:
        assert set(prog["focusEx"][f]) <= known, f
        L.append("            " + arr(prog["focusEx"][f]) + ",")
    L.append("    };")
    L.append("}")
    OUT.write_text("\n".join(L) + "\n", encoding="utf-8")
    print(f"wrote {OUT.relative_to(ROOT)}: {len(ids)} exercises, {len(prog['active'])} programs, {len(conds)} states, {len(focus)} zones")


if __name__ == "__main__":
    main()
