.class public final Lorg/apache/poi/hssf/record/chart/TextRecord;
.super Lorg/apache/poi/hssf/record/StandardRecord;
.source "TextRecord.java"


# static fields
.field public static final DATA_LABEL_PLACEMENT_ABOVE:S = 0x5s

.field public static final DATA_LABEL_PLACEMENT_AUTO:S = 0x9s

.field public static final DATA_LABEL_PLACEMENT_AXIS:S = 0x4s

.field public static final DATA_LABEL_PLACEMENT_BELOW:S = 0x6s

.field public static final DATA_LABEL_PLACEMENT_CENTER:S = 0x3s

.field public static final DATA_LABEL_PLACEMENT_CHART_DEPENDENT:S = 0x0s

.field public static final DATA_LABEL_PLACEMENT_INSIDE:S = 0x2s

.field public static final DATA_LABEL_PLACEMENT_LEFT:S = 0x7s

.field public static final DATA_LABEL_PLACEMENT_OUTSIDE:S = 0x1s

.field public static final DATA_LABEL_PLACEMENT_RIGHT:S = 0x8s

.field public static final DATA_LABEL_PLACEMENT_USER_MOVED:S = 0xas

.field public static final DISPLAY_MODE_OPAQUE:S = 0x2s

.field public static final DISPLAY_MODE_TRANSPARENT:S = 0x1s

.field public static final HORIZONTAL_ALIGNMENT_BOTTOM:B = 0x3t

.field public static final HORIZONTAL_ALIGNMENT_CENTER:B = 0x2t

.field public static final HORIZONTAL_ALIGNMENT_JUSTIFY:B = 0x4t

.field public static final HORIZONTAL_ALIGNMENT_LEFT:B = 0x1t

.field public static final ROTATION_NONE:S = 0x0s

.field public static final ROTATION_ROTATED_90_DEGREES:S = 0x2s

.field public static final ROTATION_ROTATED_90_DEGREES_CLOCKWISE:S = 0x3s

.field public static final ROTATION_TOP_TO_BOTTOM:S = 0x1s

.field public static final VERTICAL_ALIGNMENT_BOTTOM:B = 0x3t

.field public static final VERTICAL_ALIGNMENT_CENTER:B = 0x2t

.field public static final VERTICAL_ALIGNMENT_JUSTIFY:B = 0x4t

.field public static final VERTICAL_ALIGNMENT_TOP:B = 0x1t

.field private static final autoBackground:Lorg/apache/poi/util/BitField;

.field private static final autoColor:Lorg/apache/poi/util/BitField;

.field private static final autoGeneratedText:Lorg/apache/poi/util/BitField;

.field private static final autoLabelDeleted:Lorg/apache/poi/util/BitField;

.field private static final dataLabelPlacement:Lorg/apache/poi/util/BitField;

.field private static final generated:Lorg/apache/poi/util/BitField;

.field private static final rotation:Lorg/apache/poi/util/BitField;

.field private static final showBubbleSizes:Lorg/apache/poi/util/BitField;

.field private static final showCategoryLabelAsPercentage:Lorg/apache/poi/util/BitField;

.field private static final showKey:Lorg/apache/poi/util/BitField;

.field private static final showLabel:Lorg/apache/poi/util/BitField;

.field private static final showValue:Lorg/apache/poi/util/BitField;

.field private static final showValueAsPercentage:Lorg/apache/poi/util/BitField;

.field public static final sid:S = 0x1025s

.field private static final vertical:Lorg/apache/poi/util/BitField;


# instance fields
.field private field_10_indexOfColorValue:S

.field private field_11_options2:S

.field private field_12_textRotation:S

.field private field_1_horizontalAlignment:B

.field private field_2_verticalAlignment:B

.field private field_3_displayMode:S

.field private field_4_rgbColor:I

.field private field_5_x:I

.field private field_6_y:I

.field private field_7_width:I

.field private field_8_height:I

.field private field_9_options1:S


# direct methods
.method static constructor <clinit>()V
    .locals 1

    .line 35
    const/16 v0, 0xf

    invoke-static {v0}, Lorg/apache/poi/util/BitFieldFactory;->getInstance(I)Lorg/apache/poi/util/BitField;

    move-result-object v0

    sput-object v0, Lorg/apache/poi/hssf/record/chart/TextRecord;->dataLabelPlacement:Lorg/apache/poi/util/BitField;

    .line 36
    const/4 v0, 0x1

    invoke-static {v0}, Lorg/apache/poi/util/BitFieldFactory;->getInstance(I)Lorg/apache/poi/util/BitField;

    move-result-object v0

    sput-object v0, Lorg/apache/poi/hssf/record/chart/TextRecord;->autoColor:Lorg/apache/poi/util/BitField;

    .line 37
    const/4 v0, 0x2

    invoke-static {v0}, Lorg/apache/poi/util/BitFieldFactory;->getInstance(I)Lorg/apache/poi/util/BitField;

    move-result-object v0

    sput-object v0, Lorg/apache/poi/hssf/record/chart/TextRecord;->showKey:Lorg/apache/poi/util/BitField;

    .line 38
    const/4 v0, 0x4

    invoke-static {v0}, Lorg/apache/poi/util/BitFieldFactory;->getInstance(I)Lorg/apache/poi/util/BitField;

    move-result-object v0

    sput-object v0, Lorg/apache/poi/hssf/record/chart/TextRecord;->showValue:Lorg/apache/poi/util/BitField;

    .line 39
    const/16 v0, 0x8

    invoke-static {v0}, Lorg/apache/poi/util/BitFieldFactory;->getInstance(I)Lorg/apache/poi/util/BitField;

    move-result-object v0

    sput-object v0, Lorg/apache/poi/hssf/record/chart/TextRecord;->vertical:Lorg/apache/poi/util/BitField;

    .line 40
    const/16 v0, 0x10

    invoke-static {v0}, Lorg/apache/poi/util/BitFieldFactory;->getInstance(I)Lorg/apache/poi/util/BitField;

    move-result-object v0

    sput-object v0, Lorg/apache/poi/hssf/record/chart/TextRecord;->autoGeneratedText:Lorg/apache/poi/util/BitField;

    .line 41
    const/16 v0, 0x20

    invoke-static {v0}, Lorg/apache/poi/util/BitFieldFactory;->getInstance(I)Lorg/apache/poi/util/BitField;

    move-result-object v0

    sput-object v0, Lorg/apache/poi/hssf/record/chart/TextRecord;->generated:Lorg/apache/poi/util/BitField;

    .line 42
    const/16 v0, 0x40

    invoke-static {v0}, Lorg/apache/poi/util/BitFieldFactory;->getInstance(I)Lorg/apache/poi/util/BitField;

    move-result-object v0

    sput-object v0, Lorg/apache/poi/hssf/record/chart/TextRecord;->autoLabelDeleted:Lorg/apache/poi/util/BitField;

    .line 43
    const/16 v0, 0x80

    invoke-static {v0}, Lorg/apache/poi/util/BitFieldFactory;->getInstance(I)Lorg/apache/poi/util/BitField;

    move-result-object v0

    sput-object v0, Lorg/apache/poi/hssf/record/chart/TextRecord;->autoBackground:Lorg/apache/poi/util/BitField;

    .line 44
    const/16 v0, 0x700

    invoke-static {v0}, Lorg/apache/poi/util/BitFieldFactory;->getInstance(I)Lorg/apache/poi/util/BitField;

    move-result-object v0

    sput-object v0, Lorg/apache/poi/hssf/record/chart/TextRecord;->rotation:Lorg/apache/poi/util/BitField;

    .line 46
    const/16 v0, 0x800

    invoke-static {v0}, Lorg/apache/poi/util/BitFieldFactory;->getInstance(I)Lorg/apache/poi/util/BitField;

    move-result-object v0

    sput-object v0, Lorg/apache/poi/hssf/record/chart/TextRecord;->showCategoryLabelAsPercentage:Lorg/apache/poi/util/BitField;

    .line 47
    const/16 v0, 0x1000

    invoke-static {v0}, Lorg/apache/poi/util/BitFieldFactory;->getInstance(I)Lorg/apache/poi/util/BitField;

    move-result-object v0

    sput-object v0, Lorg/apache/poi/hssf/record/chart/TextRecord;->showValueAsPercentage:Lorg/apache/poi/util/BitField;

    .line 48
    const/16 v0, 0x2000

    invoke-static {v0}, Lorg/apache/poi/util/BitFieldFactory;->getInstance(I)Lorg/apache/poi/util/BitField;

    move-result-object v0

    sput-object v0, Lorg/apache/poi/hssf/record/chart/TextRecord;->showBubbleSizes:Lorg/apache/poi/util/BitField;

    .line 49
    const/16 v0, 0x4000

    invoke-static {v0}, Lorg/apache/poi/util/BitFieldFactory;->getInstance(I)Lorg/apache/poi/util/BitField;

    move-result-object v0

    sput-object v0, Lorg/apache/poi/hssf/record/chart/TextRecord;->showLabel:Lorg/apache/poi/util/BitField;

    return-void
.end method

.method public constructor <init>()V
    .locals 0

    .line 92
    invoke-direct {p0}, Lorg/apache/poi/hssf/record/StandardRecord;-><init>()V

    .line 94
    return-void
.end method

.method public constructor <init>(Lorg/apache/poi/hssf/record/RecordInputStream;)V
    .locals 1
    .param p1, "in"    # Lorg/apache/poi/hssf/record/RecordInputStream;

    .line 97
    invoke-direct {p0}, Lorg/apache/poi/hssf/record/StandardRecord;-><init>()V

    .line 98
    invoke-virtual {p1}, Lorg/apache/poi/hssf/record/RecordInputStream;->readByte()B

    move-result v0

    iput-byte v0, p0, Lorg/apache/poi/hssf/record/chart/TextRecord;->field_1_horizontalAlignment:B

    .line 99
    invoke-virtual {p1}, Lorg/apache/poi/hssf/record/RecordInputStream;->readByte()B

    move-result v0

    iput-byte v0, p0, Lorg/apache/poi/hssf/record/chart/TextRecord;->field_2_verticalAlignment:B

    .line 100
    invoke-virtual {p1}, Lorg/apache/poi/hssf/record/RecordInputStream;->readShort()S

    move-result v0

    iput-short v0, p0, Lorg/apache/poi/hssf/record/chart/TextRecord;->field_3_displayMode:S

    .line 101
    invoke-virtual {p1}, Lorg/apache/poi/hssf/record/RecordInputStream;->readInt()I

    move-result v0

    iput v0, p0, Lorg/apache/poi/hssf/record/chart/TextRecord;->field_4_rgbColor:I

    .line 102
    invoke-virtual {p1}, Lorg/apache/poi/hssf/record/RecordInputStream;->readInt()I

    move-result v0

    iput v0, p0, Lorg/apache/poi/hssf/record/chart/TextRecord;->field_5_x:I

    .line 103
    invoke-virtual {p1}, Lorg/apache/poi/hssf/record/RecordInputStream;->readInt()I

    move-result v0

    iput v0, p0, Lorg/apache/poi/hssf/record/chart/TextRecord;->field_6_y:I

    .line 104
    invoke-virtual {p1}, Lorg/apache/poi/hssf/record/RecordInputStream;->readInt()I

    move-result v0

    iput v0, p0, Lorg/apache/poi/hssf/record/chart/TextRecord;->field_7_width:I

    .line 105
    invoke-virtual {p1}, Lorg/apache/poi/hssf/record/RecordInputStream;->readInt()I

    move-result v0

    iput v0, p0, Lorg/apache/poi/hssf/record/chart/TextRecord;->field_8_height:I

    .line 106
    invoke-virtual {p1}, Lorg/apache/poi/hssf/record/RecordInputStream;->readShort()S

    move-result v0

    iput-short v0, p0, Lorg/apache/poi/hssf/record/chart/TextRecord;->field_9_options1:S

    .line 107
    invoke-virtual {p1}, Lorg/apache/poi/hssf/record/RecordInputStream;->readShort()S

    move-result v0

    iput-short v0, p0, Lorg/apache/poi/hssf/record/chart/TextRecord;->field_10_indexOfColorValue:S

    .line 108
    invoke-virtual {p1}, Lorg/apache/poi/hssf/record/RecordInputStream;->readShort()S

    move-result v0

    iput-short v0, p0, Lorg/apache/poi/hssf/record/chart/TextRecord;->field_11_options2:S

    .line 109
    invoke-virtual {p1}, Lorg/apache/poi/hssf/record/RecordInputStream;->readShort()S

    move-result v0

    iput-short v0, p0, Lorg/apache/poi/hssf/record/chart/TextRecord;->field_12_textRotation:S

    .line 110
    return-void
.end method


# virtual methods
.method public clone()Ljava/lang/Object;
    .locals 2

    .line 209
    new-instance v0, Lorg/apache/poi/hssf/record/chart/TextRecord;

    invoke-direct {v0}, Lorg/apache/poi/hssf/record/chart/TextRecord;-><init>()V

    .line 211
    .local v0, "rec":Lorg/apache/poi/hssf/record/chart/TextRecord;
    iget-byte v1, p0, Lorg/apache/poi/hssf/record/chart/TextRecord;->field_1_horizontalAlignment:B

    iput-byte v1, v0, Lorg/apache/poi/hssf/record/chart/TextRecord;->field_1_horizontalAlignment:B

    .line 212
    iget-byte v1, p0, Lorg/apache/poi/hssf/record/chart/TextRecord;->field_2_verticalAlignment:B

    iput-byte v1, v0, Lorg/apache/poi/hssf/record/chart/TextRecord;->field_2_verticalAlignment:B

    .line 213
    iget-short v1, p0, Lorg/apache/poi/hssf/record/chart/TextRecord;->field_3_displayMode:S

    iput-short v1, v0, Lorg/apache/poi/hssf/record/chart/TextRecord;->field_3_displayMode:S

    .line 214
    iget v1, p0, Lorg/apache/poi/hssf/record/chart/TextRecord;->field_4_rgbColor:I

    iput v1, v0, Lorg/apache/poi/hssf/record/chart/TextRecord;->field_4_rgbColor:I

    .line 215
    iget v1, p0, Lorg/apache/poi/hssf/record/chart/TextRecord;->field_5_x:I

    iput v1, v0, Lorg/apache/poi/hssf/record/chart/TextRecord;->field_5_x:I

    .line 216
    iget v1, p0, Lorg/apache/poi/hssf/record/chart/TextRecord;->field_6_y:I

    iput v1, v0, Lorg/apache/poi/hssf/record/chart/TextRecord;->field_6_y:I

    .line 217
    iget v1, p0, Lorg/apache/poi/hssf/record/chart/TextRecord;->field_7_width:I

    iput v1, v0, Lorg/apache/poi/hssf/record/chart/TextRecord;->field_7_width:I

    .line 218
    iget v1, p0, Lorg/apache/poi/hssf/record/chart/TextRecord;->field_8_height:I

    iput v1, v0, Lorg/apache/poi/hssf/record/chart/TextRecord;->field_8_height:I

    .line 219
    iget-short v1, p0, Lorg/apache/poi/hssf/record/chart/TextRecord;->field_9_options1:S

    iput-short v1, v0, Lorg/apache/poi/hssf/record/chart/TextRecord;->field_9_options1:S

    .line 220
    iget-short v1, p0, Lorg/apache/poi/hssf/record/chart/TextRecord;->field_10_indexOfColorValue:S

    iput-short v1, v0, Lorg/apache/poi/hssf/record/chart/TextRecord;->field_10_indexOfColorValue:S

    .line 221
    iget-short v1, p0, Lorg/apache/poi/hssf/record/chart/TextRecord;->field_11_options2:S

    iput-short v1, v0, Lorg/apache/poi/hssf/record/chart/TextRecord;->field_11_options2:S

    .line 222
    iget-short v1, p0, Lorg/apache/poi/hssf/record/chart/TextRecord;->field_12_textRotation:S

    iput-short v1, v0, Lorg/apache/poi/hssf/record/chart/TextRecord;->field_12_textRotation:S

    .line 223
    return-object v0
.end method

.method public getDataLabelPlacement()S
    .locals 2

    .line 705
    sget-object v0, Lorg/apache/poi/hssf/record/chart/TextRecord;->dataLabelPlacement:Lorg/apache/poi/util/BitField;

    iget-short v1, p0, Lorg/apache/poi/hssf/record/chart/TextRecord;->field_11_options2:S

    invoke-virtual {v0, v1}, Lorg/apache/poi/util/BitField;->getShortValue(S)S

    move-result v0

    return v0
.end method

.method protected getDataSize()I
    .locals 1

    .line 200
    const/16 v0, 0x20

    return v0
.end method

.method public getDisplayMode()S
    .locals 1

    .line 296
    iget-short v0, p0, Lorg/apache/poi/hssf/record/chart/TextRecord;->field_3_displayMode:S

    return v0
.end method

.method public getHeight()I
    .locals 1

    .line 381
    iget v0, p0, Lorg/apache/poi/hssf/record/chart/TextRecord;->field_8_height:I

    return v0
.end method

.method public getHorizontalAlignment()B
    .locals 1

    .line 240
    iget-byte v0, p0, Lorg/apache/poi/hssf/record/chart/TextRecord;->field_1_horizontalAlignment:B

    return v0
.end method

.method public getIndexOfColorValue()S
    .locals 1

    .line 413
    iget-short v0, p0, Lorg/apache/poi/hssf/record/chart/TextRecord;->field_10_indexOfColorValue:S

    return v0
.end method

.method public getOptions1()S
    .locals 1

    .line 397
    iget-short v0, p0, Lorg/apache/poi/hssf/record/chart/TextRecord;->field_9_options1:S

    return v0
.end method

.method public getOptions2()S
    .locals 1

    .line 429
    iget-short v0, p0, Lorg/apache/poi/hssf/record/chart/TextRecord;->field_11_options2:S

    return v0
.end method

.method public getRgbColor()I
    .locals 1

    .line 317
    iget v0, p0, Lorg/apache/poi/hssf/record/chart/TextRecord;->field_4_rgbColor:I

    return v0
.end method

.method public getRotation()S
    .locals 2

    .line 615
    sget-object v0, Lorg/apache/poi/hssf/record/chart/TextRecord;->rotation:Lorg/apache/poi/util/BitField;

    iget-short v1, p0, Lorg/apache/poi/hssf/record/chart/TextRecord;->field_9_options1:S

    invoke-virtual {v0, v1}, Lorg/apache/poi/util/BitField;->getShortValue(S)S

    move-result v0

    return v0
.end method

.method public getSid()S
    .locals 1

    .line 205
    const/16 v0, 0x1025

    return v0
.end method

.method public getTextRotation()S
    .locals 1

    .line 445
    iget-short v0, p0, Lorg/apache/poi/hssf/record/chart/TextRecord;->field_12_textRotation:S

    return v0
.end method

.method public getVerticalAlignment()B
    .locals 1

    .line 269
    iget-byte v0, p0, Lorg/apache/poi/hssf/record/chart/TextRecord;->field_2_verticalAlignment:B

    return v0
.end method

.method public getWidth()I
    .locals 1

    .line 365
    iget v0, p0, Lorg/apache/poi/hssf/record/chart/TextRecord;->field_7_width:I

    return v0
.end method

.method public getX()I
    .locals 1

    .line 333
    iget v0, p0, Lorg/apache/poi/hssf/record/chart/TextRecord;->field_5_x:I

    return v0
.end method

.method public getY()I
    .locals 1

    .line 349
    iget v0, p0, Lorg/apache/poi/hssf/record/chart/TextRecord;->field_6_y:I

    return v0
.end method

.method public isAutoBackground()Z
    .locals 2

    .line 597
    sget-object v0, Lorg/apache/poi/hssf/record/chart/TextRecord;->autoBackground:Lorg/apache/poi/util/BitField;

    iget-short v1, p0, Lorg/apache/poi/hssf/record/chart/TextRecord;->field_9_options1:S

    invoke-virtual {v0, v1}, Lorg/apache/poi/util/BitField;->isSet(I)Z

    move-result v0

    return v0
.end method

.method public isAutoColor()Z
    .locals 2

    .line 471
    sget-object v0, Lorg/apache/poi/hssf/record/chart/TextRecord;->autoColor:Lorg/apache/poi/util/BitField;

    iget-short v1, p0, Lorg/apache/poi/hssf/record/chart/TextRecord;->field_9_options1:S

    invoke-virtual {v0, v1}, Lorg/apache/poi/util/BitField;->isSet(I)Z

    move-result v0

    return v0
.end method

.method public isAutoGeneratedText()Z
    .locals 2

    .line 543
    sget-object v0, Lorg/apache/poi/hssf/record/chart/TextRecord;->autoGeneratedText:Lorg/apache/poi/util/BitField;

    iget-short v1, p0, Lorg/apache/poi/hssf/record/chart/TextRecord;->field_9_options1:S

    invoke-virtual {v0, v1}, Lorg/apache/poi/util/BitField;->isSet(I)Z

    move-result v0

    return v0
.end method

.method public isAutoLabelDeleted()Z
    .locals 2

    .line 579
    sget-object v0, Lorg/apache/poi/hssf/record/chart/TextRecord;->autoLabelDeleted:Lorg/apache/poi/util/BitField;

    iget-short v1, p0, Lorg/apache/poi/hssf/record/chart/TextRecord;->field_9_options1:S

    invoke-virtual {v0, v1}, Lorg/apache/poi/util/BitField;->isSet(I)Z

    move-result v0

    return v0
.end method

.method public isGenerated()Z
    .locals 2

    .line 561
    sget-object v0, Lorg/apache/poi/hssf/record/chart/TextRecord;->generated:Lorg/apache/poi/util/BitField;

    iget-short v1, p0, Lorg/apache/poi/hssf/record/chart/TextRecord;->field_9_options1:S

    invoke-virtual {v0, v1}, Lorg/apache/poi/util/BitField;->isSet(I)Z

    move-result v0

    return v0
.end method

.method public isShowBubbleSizes()Z
    .locals 2

    .line 669
    sget-object v0, Lorg/apache/poi/hssf/record/chart/TextRecord;->showBubbleSizes:Lorg/apache/poi/util/BitField;

    iget-short v1, p0, Lorg/apache/poi/hssf/record/chart/TextRecord;->field_9_options1:S

    invoke-virtual {v0, v1}, Lorg/apache/poi/util/BitField;->isSet(I)Z

    move-result v0

    return v0
.end method

.method public isShowCategoryLabelAsPercentage()Z
    .locals 2

    .line 633
    sget-object v0, Lorg/apache/poi/hssf/record/chart/TextRecord;->showCategoryLabelAsPercentage:Lorg/apache/poi/util/BitField;

    iget-short v1, p0, Lorg/apache/poi/hssf/record/chart/TextRecord;->field_9_options1:S

    invoke-virtual {v0, v1}, Lorg/apache/poi/util/BitField;->isSet(I)Z

    move-result v0

    return v0
.end method

.method public isShowKey()Z
    .locals 2

    .line 489
    sget-object v0, Lorg/apache/poi/hssf/record/chart/TextRecord;->showKey:Lorg/apache/poi/util/BitField;

    iget-short v1, p0, Lorg/apache/poi/hssf/record/chart/TextRecord;->field_9_options1:S

    invoke-virtual {v0, v1}, Lorg/apache/poi/util/BitField;->isSet(I)Z

    move-result v0

    return v0
.end method

.method public isShowLabel()Z
    .locals 2

    .line 687
    sget-object v0, Lorg/apache/poi/hssf/record/chart/TextRecord;->showLabel:Lorg/apache/poi/util/BitField;

    iget-short v1, p0, Lorg/apache/poi/hssf/record/chart/TextRecord;->field_9_options1:S

    invoke-virtual {v0, v1}, Lorg/apache/poi/util/BitField;->isSet(I)Z

    move-result v0

    return v0
.end method

.method public isShowValue()Z
    .locals 2

    .line 507
    sget-object v0, Lorg/apache/poi/hssf/record/chart/TextRecord;->showValue:Lorg/apache/poi/util/BitField;

    iget-short v1, p0, Lorg/apache/poi/hssf/record/chart/TextRecord;->field_9_options1:S

    invoke-virtual {v0, v1}, Lorg/apache/poi/util/BitField;->isSet(I)Z

    move-result v0

    return v0
.end method

.method public isShowValueAsPercentage()Z
    .locals 2

    .line 651
    sget-object v0, Lorg/apache/poi/hssf/record/chart/TextRecord;->showValueAsPercentage:Lorg/apache/poi/util/BitField;

    iget-short v1, p0, Lorg/apache/poi/hssf/record/chart/TextRecord;->field_9_options1:S

    invoke-virtual {v0, v1}, Lorg/apache/poi/util/BitField;->isSet(I)Z

    move-result v0

    return v0
.end method

.method public isVertical()Z
    .locals 2

    .line 525
    sget-object v0, Lorg/apache/poi/hssf/record/chart/TextRecord;->vertical:Lorg/apache/poi/util/BitField;

    iget-short v1, p0, Lorg/apache/poi/hssf/record/chart/TextRecord;->field_9_options1:S

    invoke-virtual {v0, v1}, Lorg/apache/poi/util/BitField;->isSet(I)Z

    move-result v0

    return v0
.end method

.method public serialize(Lorg/apache/poi/util/LittleEndianOutput;)V
    .locals 1
    .param p1, "out"    # Lorg/apache/poi/util/LittleEndianOutput;

    .line 185
    iget-byte v0, p0, Lorg/apache/poi/hssf/record/chart/TextRecord;->field_1_horizontalAlignment:B

    invoke-interface {p1, v0}, Lorg/apache/poi/util/LittleEndianOutput;->writeByte(I)V

    .line 186
    iget-byte v0, p0, Lorg/apache/poi/hssf/record/chart/TextRecord;->field_2_verticalAlignment:B

    invoke-interface {p1, v0}, Lorg/apache/poi/util/LittleEndianOutput;->writeByte(I)V

    .line 187
    iget-short v0, p0, Lorg/apache/poi/hssf/record/chart/TextRecord;->field_3_displayMode:S

    invoke-interface {p1, v0}, Lorg/apache/poi/util/LittleEndianOutput;->writeShort(I)V

    .line 188
    iget v0, p0, Lorg/apache/poi/hssf/record/chart/TextRecord;->field_4_rgbColor:I

    invoke-interface {p1, v0}, Lorg/apache/poi/util/LittleEndianOutput;->writeInt(I)V

    .line 189
    iget v0, p0, Lorg/apache/poi/hssf/record/chart/TextRecord;->field_5_x:I

    invoke-interface {p1, v0}, Lorg/apache/poi/util/LittleEndianOutput;->writeInt(I)V

    .line 190
    iget v0, p0, Lorg/apache/poi/hssf/record/chart/TextRecord;->field_6_y:I

    invoke-interface {p1, v0}, Lorg/apache/poi/util/LittleEndianOutput;->writeInt(I)V

    .line 191
    iget v0, p0, Lorg/apache/poi/hssf/record/chart/TextRecord;->field_7_width:I

    invoke-interface {p1, v0}, Lorg/apache/poi/util/LittleEndianOutput;->writeInt(I)V

    .line 192
    iget v0, p0, Lorg/apache/poi/hssf/record/chart/TextRecord;->field_8_height:I

    invoke-interface {p1, v0}, Lorg/apache/poi/util/LittleEndianOutput;->writeInt(I)V

    .line 193
    iget-short v0, p0, Lorg/apache/poi/hssf/record/chart/TextRecord;->field_9_options1:S

    invoke-interface {p1, v0}, Lorg/apache/poi/util/LittleEndianOutput;->writeShort(I)V

    .line 194
    iget-short v0, p0, Lorg/apache/poi/hssf/record/chart/TextRecord;->field_10_indexOfColorValue:S

    invoke-interface {p1, v0}, Lorg/apache/poi/util/LittleEndianOutput;->writeShort(I)V

    .line 195
    iget-short v0, p0, Lorg/apache/poi/hssf/record/chart/TextRecord;->field_11_options2:S

    invoke-interface {p1, v0}, Lorg/apache/poi/util/LittleEndianOutput;->writeShort(I)V

    .line 196
    iget-short v0, p0, Lorg/apache/poi/hssf/record/chart/TextRecord;->field_12_textRotation:S

    invoke-interface {p1, v0}, Lorg/apache/poi/util/LittleEndianOutput;->writeShort(I)V

    .line 197
    return-void
.end method

.method public setAutoBackground(Z)V
    .locals 2
    .param p1, "value"    # Z

    .line 588
    sget-object v0, Lorg/apache/poi/hssf/record/chart/TextRecord;->autoBackground:Lorg/apache/poi/util/BitField;

    iget-short v1, p0, Lorg/apache/poi/hssf/record/chart/TextRecord;->field_9_options1:S

    invoke-virtual {v0, v1, p1}, Lorg/apache/poi/util/BitField;->setShortBoolean(SZ)S

    move-result v0

    iput-short v0, p0, Lorg/apache/poi/hssf/record/chart/TextRecord;->field_9_options1:S

    .line 589
    return-void
.end method

.method public setAutoColor(Z)V
    .locals 2
    .param p1, "value"    # Z

    .line 462
    sget-object v0, Lorg/apache/poi/hssf/record/chart/TextRecord;->autoColor:Lorg/apache/poi/util/BitField;

    iget-short v1, p0, Lorg/apache/poi/hssf/record/chart/TextRecord;->field_9_options1:S

    invoke-virtual {v0, v1, p1}, Lorg/apache/poi/util/BitField;->setShortBoolean(SZ)S

    move-result v0

    iput-short v0, p0, Lorg/apache/poi/hssf/record/chart/TextRecord;->field_9_options1:S

    .line 463
    return-void
.end method

.method public setAutoGeneratedText(Z)V
    .locals 2
    .param p1, "value"    # Z

    .line 534
    sget-object v0, Lorg/apache/poi/hssf/record/chart/TextRecord;->autoGeneratedText:Lorg/apache/poi/util/BitField;

    iget-short v1, p0, Lorg/apache/poi/hssf/record/chart/TextRecord;->field_9_options1:S

    invoke-virtual {v0, v1, p1}, Lorg/apache/poi/util/BitField;->setShortBoolean(SZ)S

    move-result v0

    iput-short v0, p0, Lorg/apache/poi/hssf/record/chart/TextRecord;->field_9_options1:S

    .line 535
    return-void
.end method

.method public setAutoLabelDeleted(Z)V
    .locals 2
    .param p1, "value"    # Z

    .line 570
    sget-object v0, Lorg/apache/poi/hssf/record/chart/TextRecord;->autoLabelDeleted:Lorg/apache/poi/util/BitField;

    iget-short v1, p0, Lorg/apache/poi/hssf/record/chart/TextRecord;->field_9_options1:S

    invoke-virtual {v0, v1, p1}, Lorg/apache/poi/util/BitField;->setShortBoolean(SZ)S

    move-result v0

    iput-short v0, p0, Lorg/apache/poi/hssf/record/chart/TextRecord;->field_9_options1:S

    .line 571
    return-void
.end method

.method public setDataLabelPlacement(S)V
    .locals 2
    .param p1, "value"    # S

    .line 696
    sget-object v0, Lorg/apache/poi/hssf/record/chart/TextRecord;->dataLabelPlacement:Lorg/apache/poi/util/BitField;

    iget-short v1, p0, Lorg/apache/poi/hssf/record/chart/TextRecord;->field_11_options2:S

    invoke-virtual {v0, v1, p1}, Lorg/apache/poi/util/BitField;->setShortValue(SS)S

    move-result v0

    iput-short v0, p0, Lorg/apache/poi/hssf/record/chart/TextRecord;->field_11_options2:S

    .line 697
    return-void
.end method

.method public setDisplayMode(S)V
    .locals 0
    .param p1, "field_3_displayMode"    # S

    .line 309
    iput-short p1, p0, Lorg/apache/poi/hssf/record/chart/TextRecord;->field_3_displayMode:S

    .line 310
    return-void
.end method

.method public setGenerated(Z)V
    .locals 2
    .param p1, "value"    # Z

    .line 552
    sget-object v0, Lorg/apache/poi/hssf/record/chart/TextRecord;->generated:Lorg/apache/poi/util/BitField;

    iget-short v1, p0, Lorg/apache/poi/hssf/record/chart/TextRecord;->field_9_options1:S

    invoke-virtual {v0, v1, p1}, Lorg/apache/poi/util/BitField;->setShortBoolean(SZ)S

    move-result v0

    iput-short v0, p0, Lorg/apache/poi/hssf/record/chart/TextRecord;->field_9_options1:S

    .line 553
    return-void
.end method

.method public setHeight(I)V
    .locals 0
    .param p1, "field_8_height"    # I

    .line 389
    iput p1, p0, Lorg/apache/poi/hssf/record/chart/TextRecord;->field_8_height:I

    .line 390
    return-void
.end method

.method public setHorizontalAlignment(B)V
    .locals 0
    .param p1, "field_1_horizontalAlignment"    # B

    .line 255
    iput-byte p1, p0, Lorg/apache/poi/hssf/record/chart/TextRecord;->field_1_horizontalAlignment:B

    .line 256
    return-void
.end method

.method public setIndexOfColorValue(S)V
    .locals 0
    .param p1, "field_10_indexOfColorValue"    # S

    .line 421
    iput-short p1, p0, Lorg/apache/poi/hssf/record/chart/TextRecord;->field_10_indexOfColorValue:S

    .line 422
    return-void
.end method

.method public setOptions1(S)V
    .locals 0
    .param p1, "field_9_options1"    # S

    .line 405
    iput-short p1, p0, Lorg/apache/poi/hssf/record/chart/TextRecord;->field_9_options1:S

    .line 406
    return-void
.end method

.method public setOptions2(S)V
    .locals 0
    .param p1, "field_11_options2"    # S

    .line 437
    iput-short p1, p0, Lorg/apache/poi/hssf/record/chart/TextRecord;->field_11_options2:S

    .line 438
    return-void
.end method

.method public setRgbColor(I)V
    .locals 0
    .param p1, "field_4_rgbColor"    # I

    .line 325
    iput p1, p0, Lorg/apache/poi/hssf/record/chart/TextRecord;->field_4_rgbColor:I

    .line 326
    return-void
.end method

.method public setRotation(S)V
    .locals 2
    .param p1, "value"    # S

    .line 606
    sget-object v0, Lorg/apache/poi/hssf/record/chart/TextRecord;->rotation:Lorg/apache/poi/util/BitField;

    iget-short v1, p0, Lorg/apache/poi/hssf/record/chart/TextRecord;->field_9_options1:S

    invoke-virtual {v0, v1, p1}, Lorg/apache/poi/util/BitField;->setShortValue(SS)S

    move-result v0

    iput-short v0, p0, Lorg/apache/poi/hssf/record/chart/TextRecord;->field_9_options1:S

    .line 607
    return-void
.end method

.method public setShowBubbleSizes(Z)V
    .locals 2
    .param p1, "value"    # Z

    .line 660
    sget-object v0, Lorg/apache/poi/hssf/record/chart/TextRecord;->showBubbleSizes:Lorg/apache/poi/util/BitField;

    iget-short v1, p0, Lorg/apache/poi/hssf/record/chart/TextRecord;->field_9_options1:S

    invoke-virtual {v0, v1, p1}, Lorg/apache/poi/util/BitField;->setShortBoolean(SZ)S

    move-result v0

    iput-short v0, p0, Lorg/apache/poi/hssf/record/chart/TextRecord;->field_9_options1:S

    .line 661
    return-void
.end method

.method public setShowCategoryLabelAsPercentage(Z)V
    .locals 2
    .param p1, "value"    # Z

    .line 624
    sget-object v0, Lorg/apache/poi/hssf/record/chart/TextRecord;->showCategoryLabelAsPercentage:Lorg/apache/poi/util/BitField;

    iget-short v1, p0, Lorg/apache/poi/hssf/record/chart/TextRecord;->field_9_options1:S

    invoke-virtual {v0, v1, p1}, Lorg/apache/poi/util/BitField;->setShortBoolean(SZ)S

    move-result v0

    iput-short v0, p0, Lorg/apache/poi/hssf/record/chart/TextRecord;->field_9_options1:S

    .line 625
    return-void
.end method

.method public setShowKey(Z)V
    .locals 2
    .param p1, "value"    # Z

    .line 480
    sget-object v0, Lorg/apache/poi/hssf/record/chart/TextRecord;->showKey:Lorg/apache/poi/util/BitField;

    iget-short v1, p0, Lorg/apache/poi/hssf/record/chart/TextRecord;->field_9_options1:S

    invoke-virtual {v0, v1, p1}, Lorg/apache/poi/util/BitField;->setShortBoolean(SZ)S

    move-result v0

    iput-short v0, p0, Lorg/apache/poi/hssf/record/chart/TextRecord;->field_9_options1:S

    .line 481
    return-void
.end method

.method public setShowLabel(Z)V
    .locals 2
    .param p1, "value"    # Z

    .line 678
    sget-object v0, Lorg/apache/poi/hssf/record/chart/TextRecord;->showLabel:Lorg/apache/poi/util/BitField;

    iget-short v1, p0, Lorg/apache/poi/hssf/record/chart/TextRecord;->field_9_options1:S

    invoke-virtual {v0, v1, p1}, Lorg/apache/poi/util/BitField;->setShortBoolean(SZ)S

    move-result v0

    iput-short v0, p0, Lorg/apache/poi/hssf/record/chart/TextRecord;->field_9_options1:S

    .line 679
    return-void
.end method

.method public setShowValue(Z)V
    .locals 2
    .param p1, "value"    # Z

    .line 498
    sget-object v0, Lorg/apache/poi/hssf/record/chart/TextRecord;->showValue:Lorg/apache/poi/util/BitField;

    iget-short v1, p0, Lorg/apache/poi/hssf/record/chart/TextRecord;->field_9_options1:S

    invoke-virtual {v0, v1, p1}, Lorg/apache/poi/util/BitField;->setShortBoolean(SZ)S

    move-result v0

    iput-short v0, p0, Lorg/apache/poi/hssf/record/chart/TextRecord;->field_9_options1:S

    .line 499
    return-void
.end method

.method public setShowValueAsPercentage(Z)V
    .locals 2
    .param p1, "value"    # Z

    .line 642
    sget-object v0, Lorg/apache/poi/hssf/record/chart/TextRecord;->showValueAsPercentage:Lorg/apache/poi/util/BitField;

    iget-short v1, p0, Lorg/apache/poi/hssf/record/chart/TextRecord;->field_9_options1:S

    invoke-virtual {v0, v1, p1}, Lorg/apache/poi/util/BitField;->setShortBoolean(SZ)S

    move-result v0

    iput-short v0, p0, Lorg/apache/poi/hssf/record/chart/TextRecord;->field_9_options1:S

    .line 643
    return-void
.end method

.method public setTextRotation(S)V
    .locals 0
    .param p1, "field_12_textRotation"    # S

    .line 453
    iput-short p1, p0, Lorg/apache/poi/hssf/record/chart/TextRecord;->field_12_textRotation:S

    .line 454
    return-void
.end method

.method public setVertical(Z)V
    .locals 2
    .param p1, "value"    # Z

    .line 516
    sget-object v0, Lorg/apache/poi/hssf/record/chart/TextRecord;->vertical:Lorg/apache/poi/util/BitField;

    iget-short v1, p0, Lorg/apache/poi/hssf/record/chart/TextRecord;->field_9_options1:S

    invoke-virtual {v0, v1, p1}, Lorg/apache/poi/util/BitField;->setShortBoolean(SZ)S

    move-result v0

    iput-short v0, p0, Lorg/apache/poi/hssf/record/chart/TextRecord;->field_9_options1:S

    .line 517
    return-void
.end method

.method public setVerticalAlignment(B)V
    .locals 0
    .param p1, "field_2_verticalAlignment"    # B

    .line 284
    iput-byte p1, p0, Lorg/apache/poi/hssf/record/chart/TextRecord;->field_2_verticalAlignment:B

    .line 285
    return-void
.end method

.method public setWidth(I)V
    .locals 0
    .param p1, "field_7_width"    # I

    .line 373
    iput p1, p0, Lorg/apache/poi/hssf/record/chart/TextRecord;->field_7_width:I

    .line 374
    return-void
.end method

.method public setX(I)V
    .locals 0
    .param p1, "field_5_x"    # I

    .line 341
    iput p1, p0, Lorg/apache/poi/hssf/record/chart/TextRecord;->field_5_x:I

    .line 342
    return-void
.end method

.method public setY(I)V
    .locals 0
    .param p1, "field_6_y"    # I

    .line 357
    iput p1, p0, Lorg/apache/poi/hssf/record/chart/TextRecord;->field_6_y:I

    .line 358
    return-void
.end method

.method public toString()Ljava/lang/String;
    .locals 7

    .line 114
    new-instance v0, Ljava/lang/StringBuffer;

    invoke-direct {v0}, Ljava/lang/StringBuffer;-><init>()V

    .line 116
    .local v0, "buffer":Ljava/lang/StringBuffer;
    const-string v1, "[TEXT]\n"

    invoke-virtual {v0, v1}, Ljava/lang/StringBuffer;->append(Ljava/lang/String;)Ljava/lang/StringBuffer;

    .line 117
    const-string v1, "    .horizontalAlignment  = "

    invoke-virtual {v0, v1}, Ljava/lang/StringBuffer;->append(Ljava/lang/String;)Ljava/lang/StringBuffer;

    const-string v1, "0x"

    invoke-virtual {v0, v1}, Ljava/lang/StringBuffer;->append(Ljava/lang/String;)Ljava/lang/StringBuffer;

    invoke-virtual {p0}, Lorg/apache/poi/hssf/record/chart/TextRecord;->getHorizontalAlignment()B

    move-result v2

    invoke-static {v2}, Lorg/apache/poi/util/HexDump;->toHex(B)Ljava/lang/String;

    move-result-object v2

    invoke-virtual {v0, v2}, Ljava/lang/StringBuffer;->append(Ljava/lang/String;)Ljava/lang/StringBuffer;

    const-string v2, " ("

    invoke-virtual {v0, v2}, Ljava/lang/StringBuffer;->append(Ljava/lang/String;)Ljava/lang/StringBuffer;

    invoke-virtual {p0}, Lorg/apache/poi/hssf/record/chart/TextRecord;->getHorizontalAlignment()B

    move-result v3

    invoke-virtual {v0, v3}, Ljava/lang/StringBuffer;->append(I)Ljava/lang/StringBuffer;

    const-string v3, " )"

    invoke-virtual {v0, v3}, Ljava/lang/StringBuffer;->append(Ljava/lang/String;)Ljava/lang/StringBuffer;

    .line 120
    const-string v4, "line.separator"

    invoke-static {v4}, Ljava/lang/System;->getProperty(Ljava/lang/String;)Ljava/lang/String;

    move-result-object v5

    invoke-virtual {v0, v5}, Ljava/lang/StringBuffer;->append(Ljava/lang/String;)Ljava/lang/StringBuffer;

    .line 121
    const-string v5, "    .verticalAlignment    = "

    invoke-virtual {v0, v5}, Ljava/lang/StringBuffer;->append(Ljava/lang/String;)Ljava/lang/StringBuffer;

    invoke-virtual {v0, v1}, Ljava/lang/StringBuffer;->append(Ljava/lang/String;)Ljava/lang/StringBuffer;

    invoke-virtual {p0}, Lorg/apache/poi/hssf/record/chart/TextRecord;->getVerticalAlignment()B

    move-result v5

    invoke-static {v5}, Lorg/apache/poi/util/HexDump;->toHex(B)Ljava/lang/String;

    move-result-object v5

    invoke-virtual {v0, v5}, Ljava/lang/StringBuffer;->append(Ljava/lang/String;)Ljava/lang/StringBuffer;

    invoke-virtual {v0, v2}, Ljava/lang/StringBuffer;->append(Ljava/lang/String;)Ljava/lang/StringBuffer;

    invoke-virtual {p0}, Lorg/apache/poi/hssf/record/chart/TextRecord;->getVerticalAlignment()B

    move-result v5

    invoke-virtual {v0, v5}, Ljava/lang/StringBuffer;->append(I)Ljava/lang/StringBuffer;

    invoke-virtual {v0, v3}, Ljava/lang/StringBuffer;->append(Ljava/lang/String;)Ljava/lang/StringBuffer;

    .line 124
    invoke-static {v4}, Ljava/lang/System;->getProperty(Ljava/lang/String;)Ljava/lang/String;

    move-result-object v5

    invoke-virtual {v0, v5}, Ljava/lang/StringBuffer;->append(Ljava/lang/String;)Ljava/lang/StringBuffer;

    .line 125
    const-string v5, "    .displayMode          = "

    invoke-virtual {v0, v5}, Ljava/lang/StringBuffer;->append(Ljava/lang/String;)Ljava/lang/StringBuffer;

    invoke-virtual {v0, v1}, Ljava/lang/StringBuffer;->append(Ljava/lang/String;)Ljava/lang/StringBuffer;

    invoke-virtual {p0}, Lorg/apache/poi/hssf/record/chart/TextRecord;->getDisplayMode()S

    move-result v5

    invoke-static {v5}, Lorg/apache/poi/util/HexDump;->toHex(S)Ljava/lang/String;

    move-result-object v5

    invoke-virtual {v0, v5}, Ljava/lang/StringBuffer;->append(Ljava/lang/String;)Ljava/lang/StringBuffer;

    invoke-virtual {v0, v2}, Ljava/lang/StringBuffer;->append(Ljava/lang/String;)Ljava/lang/StringBuffer;

    invoke-virtual {p0}, Lorg/apache/poi/hssf/record/chart/TextRecord;->getDisplayMode()S

    move-result v5

    invoke-virtual {v0, v5}, Ljava/lang/StringBuffer;->append(I)Ljava/lang/StringBuffer;

    invoke-virtual {v0, v3}, Ljava/lang/StringBuffer;->append(Ljava/lang/String;)Ljava/lang/StringBuffer;

    .line 128
    invoke-static {v4}, Ljava/lang/System;->getProperty(Ljava/lang/String;)Ljava/lang/String;

    move-result-object v5

    invoke-virtual {v0, v5}, Ljava/lang/StringBuffer;->append(Ljava/lang/String;)Ljava/lang/StringBuffer;

    .line 129
    const-string v5, "    .rgbColor             = "

    invoke-virtual {v0, v5}, Ljava/lang/StringBuffer;->append(Ljava/lang/String;)Ljava/lang/StringBuffer;

    invoke-virtual {v0, v1}, Ljava/lang/StringBuffer;->append(Ljava/lang/String;)Ljava/lang/StringBuffer;

    invoke-virtual {p0}, Lorg/apache/poi/hssf/record/chart/TextRecord;->getRgbColor()I

    move-result v5

    invoke-static {v5}, Lorg/apache/poi/util/HexDump;->toHex(I)Ljava/lang/String;

    move-result-object v5

    invoke-virtual {v0, v5}, Ljava/lang/StringBuffer;->append(Ljava/lang/String;)Ljava/lang/StringBuffer;

    invoke-virtual {v0, v2}, Ljava/lang/StringBuffer;->append(Ljava/lang/String;)Ljava/lang/StringBuffer;

    invoke-virtual {p0}, Lorg/apache/poi/hssf/record/chart/TextRecord;->getRgbColor()I

    move-result v5

    invoke-virtual {v0, v5}, Ljava/lang/StringBuffer;->append(I)Ljava/lang/StringBuffer;

    invoke-virtual {v0, v3}, Ljava/lang/StringBuffer;->append(Ljava/lang/String;)Ljava/lang/StringBuffer;

    .line 132
    invoke-static {v4}, Ljava/lang/System;->getProperty(Ljava/lang/String;)Ljava/lang/String;

    move-result-object v5

    invoke-virtual {v0, v5}, Ljava/lang/StringBuffer;->append(Ljava/lang/String;)Ljava/lang/StringBuffer;

    .line 133
    const-string v5, "    .x                    = "

    invoke-virtual {v0, v5}, Ljava/lang/StringBuffer;->append(Ljava/lang/String;)Ljava/lang/StringBuffer;

    invoke-virtual {v0, v1}, Ljava/lang/StringBuffer;->append(Ljava/lang/String;)Ljava/lang/StringBuffer;

    invoke-virtual {p0}, Lorg/apache/poi/hssf/record/chart/TextRecord;->getX()I

    move-result v5

    invoke-static {v5}, Lorg/apache/poi/util/HexDump;->toHex(I)Ljava/lang/String;

    move-result-object v5

    invoke-virtual {v0, v5}, Ljava/lang/StringBuffer;->append(Ljava/lang/String;)Ljava/lang/StringBuffer;

    invoke-virtual {v0, v2}, Ljava/lang/StringBuffer;->append(Ljava/lang/String;)Ljava/lang/StringBuffer;

    invoke-virtual {p0}, Lorg/apache/poi/hssf/record/chart/TextRecord;->getX()I

    move-result v5

    invoke-virtual {v0, v5}, Ljava/lang/StringBuffer;->append(I)Ljava/lang/StringBuffer;

    invoke-virtual {v0, v3}, Ljava/lang/StringBuffer;->append(Ljava/lang/String;)Ljava/lang/StringBuffer;

    .line 136
    invoke-static {v4}, Ljava/lang/System;->getProperty(Ljava/lang/String;)Ljava/lang/String;

    move-result-object v5

    invoke-virtual {v0, v5}, Ljava/lang/StringBuffer;->append(Ljava/lang/String;)Ljava/lang/StringBuffer;

    .line 137
    const-string v5, "    .y                    = "

    invoke-virtual {v0, v5}, Ljava/lang/StringBuffer;->append(Ljava/lang/String;)Ljava/lang/StringBuffer;

    invoke-virtual {v0, v1}, Ljava/lang/StringBuffer;->append(Ljava/lang/String;)Ljava/lang/StringBuffer;

    invoke-virtual {p0}, Lorg/apache/poi/hssf/record/chart/TextRecord;->getY()I

    move-result v5

    invoke-static {v5}, Lorg/apache/poi/util/HexDump;->toHex(I)Ljava/lang/String;

    move-result-object v5

    invoke-virtual {v0, v5}, Ljava/lang/StringBuffer;->append(Ljava/lang/String;)Ljava/lang/StringBuffer;

    invoke-virtual {v0, v2}, Ljava/lang/StringBuffer;->append(Ljava/lang/String;)Ljava/lang/StringBuffer;

    invoke-virtual {p0}, Lorg/apache/poi/hssf/record/chart/TextRecord;->getY()I

    move-result v5

    invoke-virtual {v0, v5}, Ljava/lang/StringBuffer;->append(I)Ljava/lang/StringBuffer;

    invoke-virtual {v0, v3}, Ljava/lang/StringBuffer;->append(Ljava/lang/String;)Ljava/lang/StringBuffer;

    .line 140
    invoke-static {v4}, Ljava/lang/System;->getProperty(Ljava/lang/String;)Ljava/lang/String;

    move-result-object v5

    invoke-virtual {v0, v5}, Ljava/lang/StringBuffer;->append(Ljava/lang/String;)Ljava/lang/StringBuffer;

    .line 141
    const-string v5, "    .width                = "

    invoke-virtual {v0, v5}, Ljava/lang/StringBuffer;->append(Ljava/lang/String;)Ljava/lang/StringBuffer;

    invoke-virtual {v0, v1}, Ljava/lang/StringBuffer;->append(Ljava/lang/String;)Ljava/lang/StringBuffer;

    invoke-virtual {p0}, Lorg/apache/poi/hssf/record/chart/TextRecord;->getWidth()I

    move-result v5

    invoke-static {v5}, Lorg/apache/poi/util/HexDump;->toHex(I)Ljava/lang/String;

    move-result-object v5

    invoke-virtual {v0, v5}, Ljava/lang/StringBuffer;->append(Ljava/lang/String;)Ljava/lang/StringBuffer;

    invoke-virtual {v0, v2}, Ljava/lang/StringBuffer;->append(Ljava/lang/String;)Ljava/lang/StringBuffer;

    invoke-virtual {p0}, Lorg/apache/poi/hssf/record/chart/TextRecord;->getWidth()I

    move-result v5

    invoke-virtual {v0, v5}, Ljava/lang/StringBuffer;->append(I)Ljava/lang/StringBuffer;

    invoke-virtual {v0, v3}, Ljava/lang/StringBuffer;->append(Ljava/lang/String;)Ljava/lang/StringBuffer;

    .line 144
    invoke-static {v4}, Ljava/lang/System;->getProperty(Ljava/lang/String;)Ljava/lang/String;

    move-result-object v5

    invoke-virtual {v0, v5}, Ljava/lang/StringBuffer;->append(Ljava/lang/String;)Ljava/lang/StringBuffer;

    .line 145
    const-string v5, "    .height               = "

    invoke-virtual {v0, v5}, Ljava/lang/StringBuffer;->append(Ljava/lang/String;)Ljava/lang/StringBuffer;

    invoke-virtual {v0, v1}, Ljava/lang/StringBuffer;->append(Ljava/lang/String;)Ljava/lang/StringBuffer;

    invoke-virtual {p0}, Lorg/apache/poi/hssf/record/chart/TextRecord;->getHeight()I

    move-result v5

    invoke-static {v5}, Lorg/apache/poi/util/HexDump;->toHex(I)Ljava/lang/String;

    move-result-object v5

    invoke-virtual {v0, v5}, Ljava/lang/StringBuffer;->append(Ljava/lang/String;)Ljava/lang/StringBuffer;

    invoke-virtual {v0, v2}, Ljava/lang/StringBuffer;->append(Ljava/lang/String;)Ljava/lang/StringBuffer;

    invoke-virtual {p0}, Lorg/apache/poi/hssf/record/chart/TextRecord;->getHeight()I

    move-result v5

    invoke-virtual {v0, v5}, Ljava/lang/StringBuffer;->append(I)Ljava/lang/StringBuffer;

    invoke-virtual {v0, v3}, Ljava/lang/StringBuffer;->append(Ljava/lang/String;)Ljava/lang/StringBuffer;

    .line 148
    invoke-static {v4}, Ljava/lang/System;->getProperty(Ljava/lang/String;)Ljava/lang/String;

    move-result-object v5

    invoke-virtual {v0, v5}, Ljava/lang/StringBuffer;->append(Ljava/lang/String;)Ljava/lang/StringBuffer;

    .line 149
    const-string v5, "    .options1             = "

    invoke-virtual {v0, v5}, Ljava/lang/StringBuffer;->append(Ljava/lang/String;)Ljava/lang/StringBuffer;

    invoke-virtual {v0, v1}, Ljava/lang/StringBuffer;->append(Ljava/lang/String;)Ljava/lang/StringBuffer;

    invoke-virtual {p0}, Lorg/apache/poi/hssf/record/chart/TextRecord;->getOptions1()S

    move-result v5

    invoke-static {v5}, Lorg/apache/poi/util/HexDump;->toHex(S)Ljava/lang/String;

    move-result-object v5

    invoke-virtual {v0, v5}, Ljava/lang/StringBuffer;->append(Ljava/lang/String;)Ljava/lang/StringBuffer;

    invoke-virtual {v0, v2}, Ljava/lang/StringBuffer;->append(Ljava/lang/String;)Ljava/lang/StringBuffer;

    invoke-virtual {p0}, Lorg/apache/poi/hssf/record/chart/TextRecord;->getOptions1()S

    move-result v5

    invoke-virtual {v0, v5}, Ljava/lang/StringBuffer;->append(I)Ljava/lang/StringBuffer;

    invoke-virtual {v0, v3}, Ljava/lang/StringBuffer;->append(Ljava/lang/String;)Ljava/lang/StringBuffer;

    .line 152
    invoke-static {v4}, Ljava/lang/System;->getProperty(Ljava/lang/String;)Ljava/lang/String;

    move-result-object v5

    invoke-virtual {v0, v5}, Ljava/lang/StringBuffer;->append(Ljava/lang/String;)Ljava/lang/StringBuffer;

    .line 153
    const-string v5, "         .autoColor                = "

    invoke-virtual {v0, v5}, Ljava/lang/StringBuffer;->append(Ljava/lang/String;)Ljava/lang/StringBuffer;

    invoke-virtual {p0}, Lorg/apache/poi/hssf/record/chart/TextRecord;->isAutoColor()Z

    move-result v5

    invoke-virtual {v0, v5}, Ljava/lang/StringBuffer;->append(Z)Ljava/lang/StringBuffer;

    const/16 v5, 0xa

    invoke-virtual {v0, v5}, Ljava/lang/StringBuffer;->append(C)Ljava/lang/StringBuffer;

    .line 154
    const-string v6, "         .showKey                  = "

    invoke-virtual {v0, v6}, Ljava/lang/StringBuffer;->append(Ljava/lang/String;)Ljava/lang/StringBuffer;

    invoke-virtual {p0}, Lorg/apache/poi/hssf/record/chart/TextRecord;->isShowKey()Z

    move-result v6

    invoke-virtual {v0, v6}, Ljava/lang/StringBuffer;->append(Z)Ljava/lang/StringBuffer;

    invoke-virtual {v0, v5}, Ljava/lang/StringBuffer;->append(C)Ljava/lang/StringBuffer;

    .line 155
    const-string v6, "         .showValue                = "

    invoke-virtual {v0, v6}, Ljava/lang/StringBuffer;->append(Ljava/lang/String;)Ljava/lang/StringBuffer;

    invoke-virtual {p0}, Lorg/apache/poi/hssf/record/chart/TextRecord;->isShowValue()Z

    move-result v6

    invoke-virtual {v0, v6}, Ljava/lang/StringBuffer;->append(Z)Ljava/lang/StringBuffer;

    invoke-virtual {v0, v5}, Ljava/lang/StringBuffer;->append(C)Ljava/lang/StringBuffer;

    .line 156
    const-string v6, "         .vertical                 = "

    invoke-virtual {v0, v6}, Ljava/lang/StringBuffer;->append(Ljava/lang/String;)Ljava/lang/StringBuffer;

    invoke-virtual {p0}, Lorg/apache/poi/hssf/record/chart/TextRecord;->isVertical()Z

    move-result v6

    invoke-virtual {v0, v6}, Ljava/lang/StringBuffer;->append(Z)Ljava/lang/StringBuffer;

    invoke-virtual {v0, v5}, Ljava/lang/StringBuffer;->append(C)Ljava/lang/StringBuffer;

    .line 157
    const-string v6, "         .autoGeneratedText        = "

    invoke-virtual {v0, v6}, Ljava/lang/StringBuffer;->append(Ljava/lang/String;)Ljava/lang/StringBuffer;

    invoke-virtual {p0}, Lorg/apache/poi/hssf/record/chart/TextRecord;->isAutoGeneratedText()Z

    move-result v6

    invoke-virtual {v0, v6}, Ljava/lang/StringBuffer;->append(Z)Ljava/lang/StringBuffer;

    invoke-virtual {v0, v5}, Ljava/lang/StringBuffer;->append(C)Ljava/lang/StringBuffer;

    .line 158
    const-string v6, "         .generated                = "

    invoke-virtual {v0, v6}, Ljava/lang/StringBuffer;->append(Ljava/lang/String;)Ljava/lang/StringBuffer;

    invoke-virtual {p0}, Lorg/apache/poi/hssf/record/chart/TextRecord;->isGenerated()Z

    move-result v6

    invoke-virtual {v0, v6}, Ljava/lang/StringBuffer;->append(Z)Ljava/lang/StringBuffer;

    invoke-virtual {v0, v5}, Ljava/lang/StringBuffer;->append(C)Ljava/lang/StringBuffer;

    .line 159
    const-string v6, "         .autoLabelDeleted         = "

    invoke-virtual {v0, v6}, Ljava/lang/StringBuffer;->append(Ljava/lang/String;)Ljava/lang/StringBuffer;

    invoke-virtual {p0}, Lorg/apache/poi/hssf/record/chart/TextRecord;->isAutoLabelDeleted()Z

    move-result v6

    invoke-virtual {v0, v6}, Ljava/lang/StringBuffer;->append(Z)Ljava/lang/StringBuffer;

    invoke-virtual {v0, v5}, Ljava/lang/StringBuffer;->append(C)Ljava/lang/StringBuffer;

    .line 160
    const-string v6, "         .autoBackground           = "

    invoke-virtual {v0, v6}, Ljava/lang/StringBuffer;->append(Ljava/lang/String;)Ljava/lang/StringBuffer;

    invoke-virtual {p0}, Lorg/apache/poi/hssf/record/chart/TextRecord;->isAutoBackground()Z

    move-result v6

    invoke-virtual {v0, v6}, Ljava/lang/StringBuffer;->append(Z)Ljava/lang/StringBuffer;

    invoke-virtual {v0, v5}, Ljava/lang/StringBuffer;->append(C)Ljava/lang/StringBuffer;

    .line 161
    const-string v6, "         .rotation                 = "

    invoke-virtual {v0, v6}, Ljava/lang/StringBuffer;->append(Ljava/lang/String;)Ljava/lang/StringBuffer;

    invoke-virtual {p0}, Lorg/apache/poi/hssf/record/chart/TextRecord;->getRotation()S

    move-result v6

    invoke-virtual {v0, v6}, Ljava/lang/StringBuffer;->append(I)Ljava/lang/StringBuffer;

    invoke-virtual {v0, v5}, Ljava/lang/StringBuffer;->append(C)Ljava/lang/StringBuffer;

    .line 162
    const-string v6, "         .showCategoryLabelAsPercentage     = "

    invoke-virtual {v0, v6}, Ljava/lang/StringBuffer;->append(Ljava/lang/String;)Ljava/lang/StringBuffer;

    invoke-virtual {p0}, Lorg/apache/poi/hssf/record/chart/TextRecord;->isShowCategoryLabelAsPercentage()Z

    move-result v6

    invoke-virtual {v0, v6}, Ljava/lang/StringBuffer;->append(Z)Ljava/lang/StringBuffer;

    invoke-virtual {v0, v5}, Ljava/lang/StringBuffer;->append(C)Ljava/lang/StringBuffer;

    .line 163
    const-string v6, "         .showValueAsPercentage     = "

    invoke-virtual {v0, v6}, Ljava/lang/StringBuffer;->append(Ljava/lang/String;)Ljava/lang/StringBuffer;

    invoke-virtual {p0}, Lorg/apache/poi/hssf/record/chart/TextRecord;->isShowValueAsPercentage()Z

    move-result v6

    invoke-virtual {v0, v6}, Ljava/lang/StringBuffer;->append(Z)Ljava/lang/StringBuffer;

    invoke-virtual {v0, v5}, Ljava/lang/StringBuffer;->append(C)Ljava/lang/StringBuffer;

    .line 164
    const-string v6, "         .showBubbleSizes          = "

    invoke-virtual {v0, v6}, Ljava/lang/StringBuffer;->append(Ljava/lang/String;)Ljava/lang/StringBuffer;

    invoke-virtual {p0}, Lorg/apache/poi/hssf/record/chart/TextRecord;->isShowBubbleSizes()Z

    move-result v6

    invoke-virtual {v0, v6}, Ljava/lang/StringBuffer;->append(Z)Ljava/lang/StringBuffer;

    invoke-virtual {v0, v5}, Ljava/lang/StringBuffer;->append(C)Ljava/lang/StringBuffer;

    .line 165
    const-string v6, "         .showLabel                = "

    invoke-virtual {v0, v6}, Ljava/lang/StringBuffer;->append(Ljava/lang/String;)Ljava/lang/StringBuffer;

    invoke-virtual {p0}, Lorg/apache/poi/hssf/record/chart/TextRecord;->isShowLabel()Z

    move-result v6

    invoke-virtual {v0, v6}, Ljava/lang/StringBuffer;->append(Z)Ljava/lang/StringBuffer;

    invoke-virtual {v0, v5}, Ljava/lang/StringBuffer;->append(C)Ljava/lang/StringBuffer;

    .line 166
    const-string v6, "    .indexOfColorValue    = "

    invoke-virtual {v0, v6}, Ljava/lang/StringBuffer;->append(Ljava/lang/String;)Ljava/lang/StringBuffer;

    invoke-virtual {v0, v1}, Ljava/lang/StringBuffer;->append(Ljava/lang/String;)Ljava/lang/StringBuffer;

    invoke-virtual {p0}, Lorg/apache/poi/hssf/record/chart/TextRecord;->getIndexOfColorValue()S

    move-result v6

    invoke-static {v6}, Lorg/apache/poi/util/HexDump;->toHex(S)Ljava/lang/String;

    move-result-object v6

    invoke-virtual {v0, v6}, Ljava/lang/StringBuffer;->append(Ljava/lang/String;)Ljava/lang/StringBuffer;

    invoke-virtual {v0, v2}, Ljava/lang/StringBuffer;->append(Ljava/lang/String;)Ljava/lang/StringBuffer;

    invoke-virtual {p0}, Lorg/apache/poi/hssf/record/chart/TextRecord;->getIndexOfColorValue()S

    move-result v6

    invoke-virtual {v0, v6}, Ljava/lang/StringBuffer;->append(I)Ljava/lang/StringBuffer;

    invoke-virtual {v0, v3}, Ljava/lang/StringBuffer;->append(Ljava/lang/String;)Ljava/lang/StringBuffer;

    .line 169
    invoke-static {v4}, Ljava/lang/System;->getProperty(Ljava/lang/String;)Ljava/lang/String;

    move-result-object v6

    invoke-virtual {v0, v6}, Ljava/lang/StringBuffer;->append(Ljava/lang/String;)Ljava/lang/StringBuffer;

    .line 170
    const-string v6, "    .options2             = "

    invoke-virtual {v0, v6}, Ljava/lang/StringBuffer;->append(Ljava/lang/String;)Ljava/lang/StringBuffer;

    invoke-virtual {v0, v1}, Ljava/lang/StringBuffer;->append(Ljava/lang/String;)Ljava/lang/StringBuffer;

    invoke-virtual {p0}, Lorg/apache/poi/hssf/record/chart/TextRecord;->getOptions2()S

    move-result v6

    invoke-static {v6}, Lorg/apache/poi/util/HexDump;->toHex(S)Ljava/lang/String;

    move-result-object v6

    invoke-virtual {v0, v6}, Ljava/lang/StringBuffer;->append(Ljava/lang/String;)Ljava/lang/StringBuffer;

    invoke-virtual {v0, v2}, Ljava/lang/StringBuffer;->append(Ljava/lang/String;)Ljava/lang/StringBuffer;

    invoke-virtual {p0}, Lorg/apache/poi/hssf/record/chart/TextRecord;->getOptions2()S

    move-result v6

    invoke-virtual {v0, v6}, Ljava/lang/StringBuffer;->append(I)Ljava/lang/StringBuffer;

    invoke-virtual {v0, v3}, Ljava/lang/StringBuffer;->append(Ljava/lang/String;)Ljava/lang/StringBuffer;

    .line 173
    invoke-static {v4}, Ljava/lang/System;->getProperty(Ljava/lang/String;)Ljava/lang/String;

    move-result-object v6

    invoke-virtual {v0, v6}, Ljava/lang/StringBuffer;->append(Ljava/lang/String;)Ljava/lang/StringBuffer;

    .line 174
    const-string v6, "         .dataLabelPlacement       = "

    invoke-virtual {v0, v6}, Ljava/lang/StringBuffer;->append(Ljava/lang/String;)Ljava/lang/StringBuffer;

    invoke-virtual {p0}, Lorg/apache/poi/hssf/record/chart/TextRecord;->getDataLabelPlacement()S

    move-result v6

    invoke-virtual {v0, v6}, Ljava/lang/StringBuffer;->append(I)Ljava/lang/StringBuffer;

    invoke-virtual {v0, v5}, Ljava/lang/StringBuffer;->append(C)Ljava/lang/StringBuffer;

    .line 175
    const-string v5, "    .textRotation         = "

    invoke-virtual {v0, v5}, Ljava/lang/StringBuffer;->append(Ljava/lang/String;)Ljava/lang/StringBuffer;

    invoke-virtual {v0, v1}, Ljava/lang/StringBuffer;->append(Ljava/lang/String;)Ljava/lang/StringBuffer;

    invoke-virtual {p0}, Lorg/apache/poi/hssf/record/chart/TextRecord;->getTextRotation()S

    move-result v1

    invoke-static {v1}, Lorg/apache/poi/util/HexDump;->toHex(S)Ljava/lang/String;

    move-result-object v1

    invoke-virtual {v0, v1}, Ljava/lang/StringBuffer;->append(Ljava/lang/String;)Ljava/lang/StringBuffer;

    invoke-virtual {v0, v2}, Ljava/lang/StringBuffer;->append(Ljava/lang/String;)Ljava/lang/StringBuffer;

    invoke-virtual {p0}, Lorg/apache/poi/hssf/record/chart/TextRecord;->getTextRotation()S

    move-result v1

    invoke-virtual {v0, v1}, Ljava/lang/StringBuffer;->append(I)Ljava/lang/StringBuffer;

    invoke-virtual {v0, v3}, Ljava/lang/StringBuffer;->append(Ljava/lang/String;)Ljava/lang/StringBuffer;

    .line 178
    invoke-static {v4}, Ljava/lang/System;->getProperty(Ljava/lang/String;)Ljava/lang/String;

    move-result-object v1

    invoke-virtual {v0, v1}, Ljava/lang/StringBuffer;->append(Ljava/lang/String;)Ljava/lang/StringBuffer;

    .line 180
    const-string v1, "[/TEXT]\n"

    invoke-virtual {v0, v1}, Ljava/lang/StringBuffer;->append(Ljava/lang/String;)Ljava/lang/StringBuffer;

    .line 181
    invoke-virtual {v0}, Ljava/lang/StringBuffer;->toString()Ljava/lang/String;

    move-result-object v1

    return-object v1
.end method
